class KnownError(Exception):
    pass


class CommandError(Exception):
    pass
